INSERT INTO BOOKING (ID, START_DATE, END_DATE, ITEM_ID, USER_ID, STATUS)
VALUES (1, DATEADD('YEAR', -2, NOW()), DATEADD('YEAR', -1, NOW()), 1, 11, 'APPROVED');

INSERT INTO BOOKING (ID, START_DATE, END_DATE, ITEM_ID, USER_ID, STATUS)
VALUES (2, DATEADD('DAY', -7, NOW()), DATEADD('DAY', -5, NOW()), 1, 22, 'APPROVED');

INSERT INTO BOOKING (ID, START_DATE, END_DATE, ITEM_ID, USER_ID, STATUS)
VALUES (3, DATEADD('DAY', 5, NOW()), DATEADD('DAY', 7, NOW()), 1, 33, 'WAITING');

INSERT INTO BOOKING (ID, START_DATE, END_DATE, ITEM_ID, USER_ID, STATUS)
VALUES (4, DATEADD('YEAR', 1, NOW()), DATEADD('YEAR', 2, NOW()), 1, 44, 'WAITING');